// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interview_Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241112091740_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interview_Server.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterviewId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InterviewId");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            InterviewId = 1,
                            Address = "Kongens gate 6",
                            CompanyName = "PayEx",
                            Description = "Technical interview after a short speedinterview",
                            Title = "Technical Interview"
                        },
                        new
                        {
                            InterviewId = 2,
                            Address = "Idrettsveien 8",
                            CompanyName = "Nordre Follo Kommune",
                            Description = "Bli kjent intervju",
                            Title = "Førstegangsintervju"
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Logbook", b =>
                {
                    b.Property<int>("LogbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogbookId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserInterviewId")
                        .HasColumnType("integer");

                    b.HasKey("LogbookId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserInterviewId");

                    b.ToTable("Logbooks");

                    b.HasData(
                        new
                        {
                            LogbookId = 1,
                            Content = "Overall Good Interview. Need to improve something.",
                            Time = new TimeOnly(14, 30, 0),
                            Title = "Logbook from first interview",
                            UserId = 1,
                            UserInterviewId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserInterviewId")
                        .HasColumnType("integer");

                    b.HasKey("NoteId");

                    b.HasIndex("UserInterviewId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Content = "Need to smile more on interviews",
                            Status = "Reviewed",
                            Title = "Quick note from first interview",
                            UserInterviewId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogbookId")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ali@example.com",
                            LogbookId = 1,
                            Mobile = "1234",
                            PasswordHash = "AQAAAAIAAYagAAAAEFeaklhZWC73D6e3dNZiUS8ktbqzHZsWpTlAS/hGsoyxQpjMdLbu6wXeDtR+GKIATg==",
                            Username = "Ali Khan"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "muaath@example.com",
                            LogbookId = 2,
                            Mobile = "1881",
                            PasswordHash = "AQAAAAIAAYagAAAAEISzAO6CGe2IVjhYrKjkqm9R9OmdkYO2BX7dYCPsfiKOQZUARY7NBag5CVON+rTVMQ==",
                            Username = "Muaath Zerouga"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "john@example.com",
                            LogbookId = 3,
                            Mobile = "123",
                            PasswordHash = "AQAAAAIAAYagAAAAEOOPxz5qbfbU4YUUL21+wTctiKqjlovO1/oSJryhKrSdGSiPcJhqvnH4rdhTrjAsEw==",
                            Username = "John Ferdie"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "magnus@example.com",
                            LogbookId = 4,
                            Mobile = "786",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBjbcJAsCRMif9hla58OIWdKruD96qKs/lT0w5qiWuYsMkkLhReEuZyQ4/l9GhEBg==",
                            Username = "Magnus Brandsegg"
                        });
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.Property<int>("UserInterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserInterviewId"));

                    b.Property<int>("InterviewId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InterviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserInterviewId");

                    b.HasIndex("InterviewId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInterviews");

                    b.HasData(
                        new
                        {
                            UserInterviewId = 1,
                            InterviewId = 1,
                            InterviewTime = new DateTime(2024, 11, 11, 14, 30, 0, 0, DateTimeKind.Utc),
                            Role = "Interviewee",
                            Status = "Scheduled",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Logbook", b =>
                {
                    b.HasOne("Interview_Server.Models.User", "User")
                        .WithOne("Logbook")
                        .HasForeignKey("Interview_Server.Models.Logbook", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInterview", "UserInterview")
                        .WithMany()
                        .HasForeignKey("UserInterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserInterview");
                });

            modelBuilder.Entity("Interview_Server.Models.Note", b =>
                {
                    b.HasOne("UserInterview", "UserInterview")
                        .WithMany("Notes")
                        .HasForeignKey("UserInterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInterview");
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.HasOne("Interview_Server.Models.Interview", "Interview")
                        .WithMany("UserInterviews")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Server.Models.User", "User")
                        .WithMany("UserInterviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Server.Models.Interview", b =>
                {
                    b.Navigation("UserInterviews");
                });

            modelBuilder.Entity("Interview_Server.Models.User", b =>
                {
                    b.Navigation("Logbook")
                        .IsRequired();

                    b.Navigation("UserInterviews");
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
