// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interview_Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241114093910_changedLog")]
    partial class changedLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interview_Server.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kongens gate 6",
                            CompanyName = "PayEx",
                            Description = "Technical interview after a short speedinterview",
                            Title = "Technical Interview"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Idrettsveien 8",
                            CompanyName = "Nordre Follo Kommune",
                            Description = "Bli kjent intervju",
                            Title = "Førstegangsintervju"
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InterviewId")
                        .HasColumnType("integer");

                    b.Property<int>("LogbookId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.HasIndex("LogbookId");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Learned x and y",
                            InterviewId = 1,
                            LogbookId = 1,
                            Title = "Log 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Learned z and i",
                            InterviewId = 1,
                            LogbookId = 1,
                            Title = "Log 2"
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Logbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Logbooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Logbook1",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserInterviewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserInterviewId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Need to smile more on interviews",
                            Status = "Reviewed",
                            Title = "Quick note from first interview",
                            UserInterviewId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogbookId")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ali@example.com",
                            LogbookId = 1,
                            Mobile = "1234",
                            PasswordHash = "AQAAAAIAAYagAAAAEFo1KCnr/pQWqBIf2f5GblwtDjQp45J89Yqy7MNswcX8ajD2/V8nRBRAYIkD9OM+hQ==",
                            Username = "Ali Khan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "muaath@example.com",
                            LogbookId = 2,
                            Mobile = "1881",
                            PasswordHash = "AQAAAAIAAYagAAAAEFmnPKujoYk6f0oRhk7mlcXCWQ+UDZk2yf+SJPkFnigE6KgP1PrXwtcIL3Ct/zaIMg==",
                            Username = "Muaath Zerouga"
                        },
                        new
                        {
                            Id = 3,
                            Email = "john@example.com",
                            LogbookId = 3,
                            Mobile = "123",
                            PasswordHash = "AQAAAAIAAYagAAAAED/Rl6ypOMTEqgi+67Kn+WP4Qb/P5M10S0rKZ3PkCMZHxvaTSEctqvIkiVhWBOjPng==",
                            Username = "John Ferdie"
                        },
                        new
                        {
                            Id = 4,
                            Email = "magnus@example.com",
                            LogbookId = 4,
                            Mobile = "786",
                            PasswordHash = "AQAAAAIAAYagAAAAEI/mWSNIcmjz05Gv1yDpWhqBMglDPafBNLnGWZp7nxapAiTHz36/3cN16OR5ANplGA==",
                            Username = "Magnus Brandsegg"
                        });
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("InterviewId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InterviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInterviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInMinutes = 120,
                            InterviewId = 1,
                            InterviewTime = new DateTime(2024, 11, 11, 14, 30, 0, 0, DateTimeKind.Utc),
                            Role = "Interviewee",
                            Status = "Scheduled",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Interview_Server.Models.Log", b =>
                {
                    b.HasOne("Interview_Server.Models.Interview", "Interview")
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Server.Models.Logbook", "Logbook")
                        .WithMany("Logs")
                        .HasForeignKey("LogbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("Logbook");
                });

            modelBuilder.Entity("Interview_Server.Models.Logbook", b =>
                {
                    b.HasOne("Interview_Server.Models.User", "User")
                        .WithOne("Logbook")
                        .HasForeignKey("Interview_Server.Models.Logbook", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Server.Models.Note", b =>
                {
                    b.HasOne("UserInterview", "UserInterview")
                        .WithMany("Notes")
                        .HasForeignKey("UserInterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInterview");
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.HasOne("Interview_Server.Models.Interview", "Interview")
                        .WithMany("UserInterviews")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Server.Models.User", "User")
                        .WithMany("UserInterviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Server.Models.Interview", b =>
                {
                    b.Navigation("UserInterviews");
                });

            modelBuilder.Entity("Interview_Server.Models.Logbook", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Interview_Server.Models.User", b =>
                {
                    b.Navigation("Logbook")
                        .IsRequired();

                    b.Navigation("UserInterviews");
                });

            modelBuilder.Entity("UserInterview", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
